# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# This is the CI Pipeline

trigger:
  - main

pool:
  name: comp367-mac
  demands:
    - agent.name -equals MacBookPro

steps:
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'donna-sonar-pat'
      organization: 'dmvbnoob'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'dmvbnoob_comp367-project'
      cliProjectName: 'comp367-project'
      extraProperties: |
        sonar.java.binaries=target/classes

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean verify'
      javaHomeOption: 'Path'
      jdkDirectory: '/Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false

  - task: SonarCloudAnalyze@1

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'target'
      ArtifactName: 'drop'
      publishLocation: 'Container'
