# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'Donna PAT'
      organization: 'dmvbnoob'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'dmvbnoob_comp367-project'
      cliProjectName: 'comp367-project'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean verify'
      options: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.21'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false

  - task: SonarCloudAnalyze@1

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'target'
      ArtifactName: 'drop'
      publishLocation: 'Container'
